security:
  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: 86400000 # 24 * 60 * 60 * 1000 = 1일
      refresh-expiration-time: 604800000 # 7 * 24 * 60 * 60 * 1000 = 7일
      redirect-uri: http://43.200.2.168:3000/token

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          kakao-oidc-key-client:
            url: https://kauth.kakao.com
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: http://43.200.2.168:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: openid, profile_nickname, account_email  # OIDC scope 추가
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id

oauth:
  kakao:
    iss: https://kauth.kakao.com
    client-id: ${KAKAO_CLIENT_ID}