# S3
cloud:
  aws:
    s3:
      bucket: imagedata-ec2-lookie
      url: https://imagedata-ec2-lookie.s3.ap-northeast-2.amazonaws.com/images/
      expTime: 900000 # 15분
    credentials:
      access-key: AKIAZQ3DTIFA33LHORUU
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false