name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: imagedata-ec2-lookie

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        run: ./gradlew clean build --stacktrace --info

      - name: Create deploy directory
        run: mkdir -p ./deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Make zip file
        run: zip -r ./lookie.zip ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./lookie.zip s3://imagedata-ec2-lookie/

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H 43.200.2.168 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          
          scp -i ec2_key.pem lookie.zip ubuntu@43.200.2.168:/home/ubuntu/
          
          ssh -i ec2_key.pem ubuntu@43.200.2.168 << 'EOF'
            REPOSITORY=/home/ubuntu/app

            echo "> 현재 구동 중인 애플리케이션 pid 확인"
            CURRENT_PID=$(pgrep -fla java | awk '{print $1}')
            echo "현재 구동 중인 애플리케이션 pid: $CURRENT_PID"

            if [ -z "$CURRENT_PID" ]; then
              echo "현재 구동 중인 애플리케이션이 없으므로 종료하지 않습니다."
            else
              echo "> kill -15 $CURRENT_PID"
              kill -15 $CURRENT_PID
              sleep 5
            fi

            echo "> 새 애플리케이션 배포"
            unzip -o /home/ubuntu/lookie.zip -d $REPOSITORY

            JAR_NAME=$(ls -tr $REPOSITORY/*SNAPSHOT.jar | tail -n 1)
            echo "> JAR NAME: $JAR_NAME"
          
            echo "> $JAR_NAME 실행"
            nohup java -jar -Duser.timezone=Asia/Seoul "$JAR_NAME" >> "$REPOSITORY/nohup.out" 2>&1 &
          EOF
          
          rm ec2_key.pem