name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: imagedata-ec2-lookie

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # application.yml 파일 생성
      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION }}" > ./application.yml

      # application-oauth.yml 파일 생성
      - name: Create application-oauth.yml
        run: echo "${{ secrets.APPLICATION_OAUTH }}" > ./application-oauth.yml

      # application-redis.yml 파일 생성
      - name: Create application-redis.yml
        run: echo "${{ secrets.APPLICATION_REDIS }}" > ./application-redis.yml

      # application-s3.yml 파일 생성
      - name: Create application-s3.yml
        run: echo "${{ secrets.APPLICATION_S3 }}" > ./application-s3.yml

      - name: Build with Gradle
        run: ./gradlew clean build

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      # Move yml files to deploy directory
      - name: Move yml files to deploy directory
        run: |
          mv application.yml ./deploy/
          mv application-oauth.yml ./deploy/
          mv application-redis.yml ./deploy/
          mv application-s3.yml ./deploy/

      - name: Make zip file
        run: zip -r ./lookie.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./lookie.zip s3://imagedata-ec2-lookie/

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
                      --application-name lookie \
                      --deployment-group-name lookie-group \
                      --file-exists-behavior OVERWRITE \
                      --s3-location bucket=imagedata-ec2-lookie,bundleType=zip,key=lookie.zip \
                      --region ap-northeast-2
